In [2]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
boston = pd.read_csv('../BostonHousing.csv')

In [3]:
#Problem1 i)
dataset = pd.read_csv('../BostonHousing.csv')
dataset.head()


crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
y=dataset['medv']
X=dataset.drop(['medv'],axis=1,inplace=False)
X=X.to_numpy()

In [5]:
def pearson_correlation(x, y):
    # Compute means
    x_mean = np.mean(x, axis=0)
    y_mean = np.mean(y, axis=0)

    # Compute standard deviations
    x_std = np.std(x, axis=0)
    y_std = np.std(y, axis=0)

    # Compute covariance
    covariance = np.mean((x - x_mean) * (y - y_mean), axis=0)

    # Return Pearson correlation coefficient
    return covariance / (x_std * y_std)

In [6]:
# Compute Pearson correlation coefficients
#print(X[:,0])
result =[]
for i in range(0,12):
    calc_pearson = pearson_correlation(X[:,i], y)
    result.append(calc_pearson)

In [7]:
print(result)

[-0.38830460858681165, 0.36044534245054316, -0.48372516002837285, 0.1752601771902984, -0.4273207723732827, 0.6953599470715394, -0.3769545650045962, 0.2499287340859039, -0.3816262306397781, -0.468535933567767, -0.507786685537562, 0.33346081965706653]


Principal component analysis (PCA) is a statistical method that is used to reduce the dimensionality of a dataset.
It does this by finding new, lower-dimensional representations of the data that capture the most important variations in the data.

The algorithm works by first calculating the covariance matrix of the data,
which describes the correlations between the different features in the data. 
The covariance matrix is then decomposed using singular value decomposition (SVD) or eigendecomposition to find the eigenvectors and eigenvalues of the matrix.

The eigenvectors of the covariance matrix are the principal components of the data, 
and the eigenvalues describe the amount of variation in the data that is captured by each principal component. 
The PCA algorithm then selects the top k eigenvectors (where k is the number of dimensions we want to reduce the data to), and projects the data onto the new subspace defined by these k eigenvectors.

The result is a new, lower-dimensional dataset that captures the most important variations in the original data. 
This can be useful for a number of applications, such as data visualization, noise reduction, and feature extraction.

In [8]:
# ii)
import numpy as np

def pca(X, num_components):
  # Mean center the data
  X_mean = X - np.mean(X, axis=0)

  # Calculate the covariance matrix
  cov = np.cov(X_mean, rowvar=False)

  # Calculate the eigenvalues and eigenvectors of the covariance matrix
  eigenvalues, eigenvectors = np.linalg.eig(cov)

  # Sort the eigenvalues and eigenvectors in descending order
  idx = eigenvalues.argsort()[::-1]
  eigenvalues = eigenvalues[idx]
  eigenvectors = eigenvectors[:,idx]

  # Take the top `num_components` eigenvectors
  W = eigenvectors[:, :num_components]

  # Project the data onto the new subspace
  X_pca = np.dot(X_mean, W)

  return X_pca

In [9]:
pca_data = dataset.to_numpy()
pca_12com = pca(dataset,len(pca_data))
pca_12com

array([[-1.19817596e+02, -5.53898918e+00, -3.26792041e+00, ...,
         5.42164681e-02,  2.79565938e-02,  1.78979032e-02],
       [-1.68809338e+02,  1.01744592e+01, -3.10760869e+01, ...,
        -6.27963975e-02,  7.52030847e-02, -3.98505128e-02],
       [-1.69565571e+02,  1.40216969e+01, -1.61322371e+01, ...,
        -2.43410351e-01,  1.30514856e-01,  5.49956408e-03],
       ...,
       [-1.38375366e+02,  9.68067975e-01, -3.73212636e+01, ...,
        -4.39683382e-01,  6.98734040e-02,  3.23952370e-02],
       [-1.37445002e+02,  4.29816287e+00, -3.61671961e+01, ...,
        -3.64928299e-01,  5.87735280e-02,  3.33854893e-02],
       [-1.38872152e+02,  1.14494212e+00, -3.07284370e+01, ...,
        -8.21368020e-02, -3.78083159e-03,  1.88600393e-02]])

In [10]:
final_data = pca(dataset,3)
final_data

array([[-119.81759621,   -5.53898918,   -3.26792041],
       [-168.8093378 ,   10.17445922,  -31.07608687],
       [-169.56557101,   14.02169685,  -16.13223709],
       ...,
       [-138.37536643,    0.96806797,  -37.3212636 ],
       [-137.44500197,    4.29816287,  -36.16719605],
       [-138.87215156,    1.14494212,  -30.72843699]])

In [11]:
from sklearn.decomposition import PCA
#compare with sklearn dataset 
pca = PCA(n_components = 3)
pca_transformed = pca.fit_transform(dataset)
pca_transformed

dataset['pca_x'] = pca_transformed[:, 0]  #x coordinate
dataset['pca_y'] = pca_transformed[:, 1]  #y coordinate
dataset['pca_z'] = pca_transformed[:, 2]  #z coordinate

pca_transformed

array([[-119.81759621,   -5.53898918,   -3.26792041],
       [-168.8093378 ,   10.17445922,  -31.07608687],
       [-169.56557101,   14.02169685,  -16.13223709],
       ...,
       [-138.37536643,    0.96806797,  -37.3212636 ],
       [-137.44500197,    4.29816287,  -36.16719605],
       [-138.87215156,    1.14494212,  -30.72843699]])

因为上次作业没有写 k_fold,这次补交,逻辑如下<br>
1. shuffle the data to ensure that the samples are distributed randomly<br>
2. split the data into K "folds" or partitions of the data<br>
3. iterate over the folds and use each one as a validation set, while the other folds are used as the training set<br>
4. train my model using the training sets and evaluate it using the validation set<br>

In [14]:
#Logic
def k_fold(data, k, model):
    # Split the data into k folds
    folds = np.array_split(data, k)

    # Train and evaluate the model k times
    scores = []
    for i in range(k):
        # Create the training and validation sets
        train_index = np.concatenate(folds[:i] + folds[i+1:])
        val_index = folds[i]
        X_train, X_test = X[train_index], X[val_index]
        y_train, y_test = y[train_index], y[val_index]
        # Train the model on the training folds
        model.fit(train_index)

        # Evaluate the model on the validation fold
        score = model.evaluate(val_index)
        scores.append(score)

    # Average the performance metrics
    avg_score = np.mean(scores)
    return avg_score